# Generated by Django 3.1.1 on 2020-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(max_length=30, null=True)),
                ('S_class', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
