# Generated by Django 3.1.1 on 2020-11-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdriver',
            name='Citizenship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
