# Generated by Django 3.1.1 on 2020-12-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Class', '0002_auto_20201127_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='homworke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_homework', models.CharField(max_length=100)),
                ('release_time', models.DateTimeField()),
                ('Complete_time', models.DateTimeField()),
                ('carry_out', models.BooleanField(choices=[(0, 'not done'), (1, 'finished')])),
                ('id_discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_Class.discipline')),
                ('id_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_Class.schedule')),
                ('id_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_Class.teacher')),
            ],
        ),
    ]
