# Generated by Django 3.1.1 on 2020-12-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Class', '0003_homworke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homworke',
            name='id_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_Class.student'),
        ),
    ]
