# Generated by Django 3.1.1 on 2020-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Class', '0004_auto_20201224_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homworke',
            name='Complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
