# Generated by Django 3.1.1 on 2020-12-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Class', '0005_auto_20201224_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homworke',
            name='carry_out',
            field=models.BooleanField(choices=[('not done', 0), ('finished', 1)]),
        ),
    ]
