# Generated by Django 3.1.1 on 2020-12-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Class', '0006_auto_20201224_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homworke',
            name='carry_out',
            field=models.BooleanField(choices=[(0, 'not done'), (1, 'finished')]),
        ),
    ]
