# Generated by Django 3.1.1 on 2020-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='S_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
