# Generated by Django 3.1.1 on 2020-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoApp', '0002_auto_20201019_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='S_class',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
